import { invoke } from "@tauri-apps/api/core";
import { useConversationStore, useSettingsStore, useAgentStatusStore } from "@/stores";
import {
  buildActiveProfileProxyUrl,
  resolveActiveCredentials,
  getEffectiveSdk,
} from "@/lib/platform-config";
import { formatConversationTitle } from "@/lib/conversation-text";
import { resolvePaneModel } from "@/lib/pane-model";
import type { StreamRequestContext } from "@/lib/chat-stream-registry";

interface TitleInvokeArgs {
  readonly sdk: string;
  readonly model: string | undefined;
  readonly baseUrl: string | undefined;
  readonly apiKey: string | undefined;
  readonly proxyUrl: string | undefined;
}

/**
 * Build the credentials + model for title generation. Mirrors the main
 * streaming path (use-chat-streaming.ts) so a conversation's title is
 * generated by the same provider that will answer the conversation itself —
 * instead of the global active platform, which ignored the user's per-
 * conversation selection.
 *
 * Returns null when no usable credentials can be resolved; the caller falls
 * back to truncating the user message.
 */
function resolveTitleInvokeArgs(conversationId: string): TitleInvokeArgs | null {
  const modelSelection = resolvePaneModel({ conversationId });
  const settings = useSettingsStore.getState();
  const globalProxyUrl = settings.proxyEnabled && settings.proxyUrl ? settings.proxyUrl : undefined;

  if (modelSelection.requiresLocalSelection || !modelSelection.platformId) return null;

  const resolvedPlatformId = modelSelection.platformId;
  const platformConfig = settings.platforms[resolvedPlatformId];
  if (!platformConfig) return null;
  const creds = resolveActiveCredentials(platformConfig);
  if (!creds?.apiKey) return null;
  const sdk = getEffectiveSdk(platformConfig);
  const proxyUrl = sdk === "claude" ? buildActiveProfileProxyUrl(platformConfig) : globalProxyUrl;
  if (sdk === "claude" && !proxyUrl) return null;

  return {
    sdk,
    model: modelSelection.modelId || creds.model || undefined,
    baseUrl: creds.baseUrl || undefined,
    apiKey: creds.apiKey,
    proxyUrl,
  };
}

/**
 * Trigger title generation for a conversation if it still needs one.
 * Marks `ctx.titleTriggered` to prevent duplicate invocations.
 *
 * Checks the conversation's current title in the store -- only fires
 * when the title is still the default "New Chat".  This covers both
 * brand-new conversations (`isNewConversation`) and conversations that
 * were pre-created via the "New Chat" button before the user sent
 * their first message.
 */
export function triggerTitleGeneration(ctx: StreamRequestContext): void {
  if (ctx.titleTriggered) return;

  const convId = ctx.conversationId;
  if (!convId) return;

  const userMsg = ctx.firstUserMessage;
  if (!userMsg) return;

  // Only generate if the conversation still has the default placeholder title
  const conv = useConversationStore.getState().conversations.find((c) => c.id === convId);
  if (conv && conv.title !== "New Chat") return;

  ctx.titleTriggered = true;

  const fallbackTitle = () => (userMsg.length > 50 ? `${userMsg.slice(0, 50)}...` : userMsg);

  const invokeArgs = resolveTitleInvokeArgs(convId);
  if (!invokeArgs) {
    useConversationStore.getState().renameConversation(convId, fallbackTitle());
    return;
  }

  invoke<string>("generate_title", {
    sdk: invokeArgs.sdk,
    model: invokeArgs.model,
    baseUrl: invokeArgs.baseUrl,
    apiKey: invokeArgs.apiKey,
    userMessage: userMsg,
    proxyUrl: invokeArgs.proxyUrl,
  })
    .then((title) => {
      const cleanedTitle = formatConversationTitle(title);
      if (cleanedTitle && cleanedTitle !== "Untitled conversation") {
        useConversationStore.getState().renameConversation(convId, cleanedTitle);
      } else {
        useConversationStore.getState().renameConversation(convId, fallbackTitle());
      }
    })
    .catch(() => {
      useConversationStore.getState().renameConversation(convId, fallbackTitle());
    });
}

/** Finalize subagents and mark incomplete todos as completed, then persist to DB. */
export function finalizeAgentTurnAndTodos(
  conversationId: string | null,
  activeConvId: string | null,
): void {
  const agentStore = useAgentStatusStore.getState();
  const isBackground = conversationId != null && conversationId !== activeConvId;

  if (isBackground) {
    agentStore.finalizeCachedAgentTurn(conversationId!);
    agentStore.completeCachedPendingTodos(conversationId!);
  } else {
    agentStore.finalizeAgentTurn();
    agentStore.completePendingTodos();
  }

  if (conversationId) {
    const freshAgentStore = useAgentStatusStore.getState();
    const todosToSave = isBackground
      ? (freshAgentStore._agentStatusCache[conversationId]?.todos ?? [])
      : freshAgentStore.todos;
    if (todosToSave.length > 0) {
      freshAgentStore.persistTodos(conversationId, todosToSave);
    }
  }
}
