import { create } from "zustand";
import { invoke } from "@tauri-apps/api/core";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FileChange {
  readonly filePath: string;
  readonly action: "edit" | "create" | "delete";
  readonly toolName: string;
  readonly additions: number;
  readonly deletions: number;
}

/** Per-conversation file-change tracking state. */
interface ConversationFileState {
  readonly changes: ReadonlyArray<FileChange>;
  readonly userMessageUuid: string | null;
  readonly requestId: string | null;
  readonly isRewinding: boolean;
  readonly rewindError: string | null;
  /** Whether a code review AI call is in progress. */
  readonly isReviewing: boolean;
  /** Error message from the last code review attempt. */
  readonly reviewError: string | null;
  /** The review result text from the AI (markdown). */
  readonly reviewResult: string | null;
  /** Whether the review result modal should be shown. */
  readonly showReviewModal: boolean;
}

interface FileChangesState {
  /** File changes keyed by conversation ID. */
  readonly changesByConversation: Readonly<
    Record<string, ConversationFileState>
  >;
  /** Whether the file list panel is expanded (global UI state). */
  readonly isExpanded: boolean;

  // Selectors
  readonly getConversationState: (
    conversationId: string | null,
  ) => ConversationFileState;

  // Actions
  readonly addFileChange: (
    conversationId: string | null,
    change: FileChange,
  ) => void;
  readonly setUserMessageUuid: (
    conversationId: string | null,
    requestId: string,
    uuid: string,
  ) => void;
  readonly setExpanded: (expanded: boolean) => void;
  readonly toggleExpanded: () => void;
  readonly clearChanges: (conversationId: string | null) => void;
  readonly rewindFiles: (conversationId: string | null) => Promise<void>;
  readonly setRewindResult: (
    conversationId: string | null,
    success: boolean,
    error?: string,
  ) => void;
  /** Trigger an AI code review for the current session's changed files. */
  readonly reviewFiles: (conversationId: string | null) => Promise<void>;
  /** Set or clear the review result (called after AI responds). */
  readonly setReviewResult: (
    conversationId: string | null,
    result: string | null,
    error?: string,
  ) => void;
  /** Show or hide the review result modal. */
  readonly setShowReviewModal: (
    conversationId: string | null,
    show: boolean,
  ) => void;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

const EMPTY_CONVERSATION_STATE: ConversationFileState = {
  changes: [],
  userMessageUuid: null,
  requestId: null,
  isRewinding: false,
  rewindError: null,
  isReviewing: false,
  reviewError: null,
  reviewResult: null,
  showReviewModal: false,
};

/** Resolve a conversation key — use a sentinel for null/undefined IDs. */
function convKey(conversationId: string | null): string {
  return conversationId ?? "__no_conversation__";
}

/** Tracks rewind timeout handles per conversation so they can be cleared. */
const rewindTimeouts = new Map<string, ReturnType<typeof setTimeout>>();

export const useFileChangesStore = create<FileChangesState>((set, get) => ({
  changesByConversation: {},
  isExpanded: false,

  getConversationState: (conversationId) => {
    const key = convKey(conversationId);
    return get().changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
  },

  addFileChange: (conversationId, change) => {
    const key = convKey(conversationId);
    set((state) => {
      const prev =
        state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
      // Deduplicate: if same file already tracked, merge stats
      const existing = prev.changes.findIndex(
        (c) => c.filePath === change.filePath,
      );
      let updatedChanges: ReadonlyArray<FileChange>;
      if (existing >= 0) {
        updatedChanges = prev.changes.map((c, i) =>
          i === existing
            ? {
                ...c,
                action: change.action,
                additions: c.additions + change.additions,
                deletions: c.deletions + change.deletions,
              }
            : c,
        );
      } else {
        updatedChanges = [...prev.changes, change];
      }
      return {
        changesByConversation: {
          ...state.changesByConversation,
          [key]: { ...prev, changes: updatedChanges },
        },
      };
    });
  },

  setUserMessageUuid: (conversationId, requestId, uuid) => {
    const key = convKey(conversationId);
    // Always update — the UUID is pre-generated by the sidecar and
    // corresponds exactly to the CLI's checkpoint messageId.
    // On retry, a new UUID replaces the stale one.
    set((state) => {
      const prev =
        state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
      return {
        changesByConversation: {
          ...state.changesByConversation,
          [key]: { ...prev, requestId, userMessageUuid: uuid },
        },
      };
    });
  },

  setExpanded: (expanded) => {
    set({ isExpanded: expanded });
  },

  toggleExpanded: () => {
    set((state) => ({ isExpanded: !state.isExpanded }));
  },

  clearChanges: (conversationId) => {
    const key = convKey(conversationId);
    set((state) => ({
      changesByConversation: {
        ...state.changesByConversation,
        [key]: EMPTY_CONVERSATION_STATE,
      },
      isExpanded: false,
    }));
  },

  rewindFiles: async (conversationId) => {
    const key = convKey(conversationId);
    const convState =
      get().changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
    const { requestId, userMessageUuid } = convState;
    if (!requestId || !userMessageUuid) {
      set((state) => ({
        changesByConversation: {
          ...state.changesByConversation,
          [key]: {
            ...convState,
            rewindError: "No checkpoint available for rewind.",
          },
        },
      }));
      return;
    }

    set((state) => ({
      changesByConversation: {
        ...state.changesByConversation,
        [key]: { ...convState, isRewinding: true, rewindError: null },
      },
    }));

    // Safety timeout: if the chat-rewind-result event never arrives,
    // reset isRewinding after 15 seconds to avoid a permanent spinner.
    const prevTimeout = rewindTimeouts.get(key);
    if (prevTimeout) clearTimeout(prevTimeout);

    const timeoutId = setTimeout(() => {
      rewindTimeouts.delete(key);
      const current =
        get().changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
      if (current.isRewinding) {
        set((state) => ({
          changesByConversation: {
            ...state.changesByConversation,
            [key]: {
              ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
              isRewinding: false,
              rewindError: "Rewind timed out — no response from backend.",
            },
          },
        }));
      }
    }, 15_000);
    rewindTimeouts.set(key, timeoutId);

    try {
      await invoke("rewind_files", {
        requestId,
        userMessageUuid,
      });
      // Result will arrive via chat-rewind-result event.
      // The timeout above acts as a safety net in case the event is lost.
    } catch (err: unknown) {
      const existing = rewindTimeouts.get(key);
      if (existing) {
        clearTimeout(existing);
        rewindTimeouts.delete(key);
      }
      const errorMsg = err instanceof Error ? err.message : String(err);
      set((state) => {
        const current =
          state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
        return {
          changesByConversation: {
            ...state.changesByConversation,
            [key]: { ...current, isRewinding: false, rewindError: errorMsg },
          },
        };
      });
    }
  },

  setRewindResult: (conversationId, success, error) => {
    const key = convKey(conversationId);
    // Clear the safety timeout since we received the result normally.
    const pendingTimeout = rewindTimeouts.get(key);
    if (pendingTimeout) {
      clearTimeout(pendingTimeout);
      rewindTimeouts.delete(key);
    }
    set((state) => {
      const prev =
        state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
      return {
        changesByConversation: {
          ...state.changesByConversation,
          [key]: {
            ...prev,
            isRewinding: false,
            rewindError: success ? null : (error ?? "Rewind failed"),
            ...(success ? { changes: [] } : {}),
          },
        },
        // Collapse the file list panel when rewind succeeds (no files left).
        ...(success ? { isExpanded: false } : {}),
      };
    });
  },

  reviewFiles: async (conversationId) => {
    const key = convKey(conversationId);
    const convState =
      get().changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;

    if (convState.changes.length === 0) return;
    // Prevent concurrent reviews for the same conversation
    if (convState.isReviewing) return;

    // Snapshot changes at invocation time — review is based on what was
    // visible when the user clicked, not what may arrive during the API call.
    const changes = [...convState.changes];

    // Mark as reviewing
    set((state) => ({
      changesByConversation: {
        ...state.changesByConversation,
        [key]: {
          ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
          isReviewing: true,
          reviewError: null,
          reviewResult: null,
          showReviewModal: false,
        },
      },
    }));

    try {
      // Dynamic imports to avoid circular dependency:
      // file-changes-store → code-review-service → file-changes-store (type)
      const [{ performCodeReviewStreaming }, { buildActiveProfileProxyUrl, resolveActiveCredentials, getEffectiveSdk }, { useSettingsStore }, { useWorkspaceStore }] =
        await Promise.all([
          import("@/lib/code-review-service"),
          import("@/lib/platform-config"),
          import("@/stores/settings-store"),
          import("@/stores/workspace-store"),
        ]);

      const settings = useSettingsStore.getState();
      const workspacePath = useWorkspaceStore.getState().activeWorkspace?.path ?? "";
      const platformConfig = settings.platforms[settings.activePlatformId];
      const creds = resolveActiveCredentials(platformConfig);
      const sdk = getEffectiveSdk(platformConfig);
      const proxyUrl =
        sdk === "claude"
          ? buildActiveProfileProxyUrl(platformConfig)
          : settings.proxyEnabled && settings.proxyUrl
            ? settings.proxyUrl
            : undefined;

      const providerConfig = {
        sdk,
        baseUrl: creds?.baseUrl ?? "",
        apiKey: creds?.apiKey ?? "",
        model: creds?.model ?? platformConfig.activeModelId,
        proxyUrl,
      };

      // Show modal immediately before the first delta arrives so the user
      // sees the loading spinner rather than a blank screen.
      set((state) => ({
        changesByConversation: {
          ...state.changesByConversation,
          [key]: {
            ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
            showReviewModal: true,
            reviewResult: null,
            reviewError: null,
          },
        },
      }));

      await performCodeReviewStreaming(
        { changes, providerConfig, workspacePath },
        // onDelta — append each chunk to reviewResult in the store
        (chunk) => {
          set((state) => {
            const conv =
              state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE;
            return {
              changesByConversation: {
                ...state.changesByConversation,
                [key]: {
                  ...conv,
                  reviewResult: (conv.reviewResult ?? "") + chunk,
                },
              },
            };
          });
        },
        // onDone — mark reviewing complete
        () => {
          set((state) => ({
            changesByConversation: {
              ...state.changesByConversation,
              [key]: {
                ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
                isReviewing: false,
                reviewError: null,
              },
            },
          }));
        },
        // onError — show error, close modal
        (errorMsg) => {
          set((state) => ({
            changesByConversation: {
              ...state.changesByConversation,
              [key]: {
                ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
                isReviewing: false,
                reviewError: errorMsg,
                reviewResult: null,
                showReviewModal: false,
              },
            },
          }));
        },
      );
    } catch (err: unknown) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set((state) => ({
        changesByConversation: {
          ...state.changesByConversation,
          [key]: {
            ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
            isReviewing: false,
            reviewError: errorMsg,
            reviewResult: null,
            showReviewModal: false,
          },
        },
      }));
    }
  },

  setReviewResult: (conversationId, result, error) => {
    const key = convKey(conversationId);
    set((state) => ({
      changesByConversation: {
        ...state.changesByConversation,
        [key]: {
          ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
          isReviewing: false,
          reviewResult: result,
          reviewError: error ?? null,
          showReviewModal: result !== null,
        },
      },
    }));
  },

  setShowReviewModal: (conversationId, show) => {
    const key = convKey(conversationId);
    set((state) => ({
      changesByConversation: {
        ...state.changesByConversation,
        [key]: {
          ...(state.changesByConversation[key] ?? EMPTY_CONVERSATION_STATE),
          showReviewModal: show,
        },
      },
    }));
  },
}));
